<?php
if(isset($_POST['your_help'])){
	include('connection.php');
	$email = $_POST['email'];
	$course = $_POST['course'];
	$pages = $_POST['pages'];	
	$orderid =(rand(100,100000));//To be generated by a random variable
	$price = ($pages * 10);
	
	/*check if username exists------here will check order number if exists 
$checksql = "SELECT UserName FROM orders WHERE orderid='".$orderid."'";
$quryres = mysqli_query($db, $checksql);
$count = mysqli_num_rows($quryres);		
	if($count>0){
		echo"<div style='margin:auto;padding:2px;background:#dd7388;font-family:Segoe UI;border-radius:2px;color:#660606;'>
		<strong>Registration failed!</strong> Username <font style='color:black;'>".$unr."</font> already exists.Choose another one and try again.
		</div>";		
	}
	
	
else{*/
			
$sql = "INSERT INTO orders (email,course,pages,orderid,price)
        VALUES('".$email."','".$course."','".$pages."','".$orderid."','".$price."')";


$qury = mysqli_query($db, $sql);

if(!$qury){
	echo"<div style='margin:auto;padding:2px;background:#dd7388;font-family:Segoe UI;border-radius:2px;color:#660606;'>
		<strong>Order placement failed!</strong>".mysqli_error($db)."</div>";
}
   else{
	 echo"<div style='margin:auto;padding:2px;background:#61dd37;font-family:Segoe UI;border-radius:2px;color:#144404;'>
		<strong>Success!</strong> Order id successfully placed ".$orderid."</div>";
		header("location:orderdetails.php"); //Redirecting to the orderdetails page
   }
	   
	 }
//}

?>